server:
  port: 8082
spring:
  application:
    name: product-service
  mongodb:
    #for local testing, use the following URI
    # uri: ${MONGODB_URI:mongodb://localhost:27017/productservice}
    #for production, use the following URI (replace with your actual MongoDB Atlas URI)
    uri: ${MONGODB_URI:mongodb://localhost:27017/productservice}

  web:
    error:
      include-message: always
      include-stacktrace: on_param
      include-binding-errors: always
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false
    consumer:
      group-id: product-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.use.type.headers: false
eureka:
  client:
    enabled: true # Set to true if using Eureka for service discovery
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info

jwt:
  secret: E-commerceFreshCart-WebSite-SecretKey
  expiration: 600000 # 10 minutes
  server:
  port: 8082

app:
  kafka:
    topics:
      product-deleted: product.deleted
      order-created: order.created
