server:
  port: 8081

spring:
  application:
    name: user-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/users_db}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:0000}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: sandbox.smtp.mailtrap.io
    port: 587
    username: d037739bf776cd
    password: 3c19742c27fbe6
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false

jwt:
  secret: E-commerceFreshCart-WebSite-SecretKey
  expiration-ms: 604800000 # 7 days in milliseconds

encryption:
  secret-key: tmZkmZwPuBBaYn9wElpWl+/DPSiQGrgGyxgZtoqaujY=
eureka:
  client:
    enabled: true
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info

app:
  kafka:
    topics:
      user-registered: user.registered
      user-deleted: user.deleted
